//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("EmpresasModel", "Empresa_Empleado_FK1", "Empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaDatos.Empresa), "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaDatos.Empleado), true)]

#endregion

namespace CapaDatos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EmpresasEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EmpresasEntities usando la cadena de conexión encontrada en la sección 'EmpresasEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public EmpresasEntities() : base("name=EmpresasEntities", "EmpresasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EmpresasEntities.
        /// </summary>
        public EmpresasEntities(string connectionString) : base(connectionString, "EmpresasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EmpresasEntities.
        /// </summary>
        public EmpresasEntities(EntityConnection connection) : base(connection, "EmpresasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empleado> Empleado
        {
            get
            {
                if ((_Empleado == null))
                {
                    _Empleado = base.CreateObjectSet<Empleado>("Empleado");
                }
                return _Empleado;
            }
        }
        private ObjectSet<Empleado> _Empleado;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empresa> Empresa
        {
            get
            {
                if ((_Empresa == null))
                {
                    _Empresa = base.CreateObjectSet<Empresa>("Empresa");
                }
                return _Empresa;
            }
        }
        private ObjectSet<Empresa> _Empresa;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Empleado. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpleado(Empleado empleado)
        {
            base.AddObject("Empleado", empleado);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Empresa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpresa(Empresa empresa)
        {
            base.AddObject("Empresa", empresa);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmpresasModel", Name="Empleado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empleado : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empleado.
        /// </summary>
        /// <param name="rut">Valor inicial de la propiedad Rut.</param>
        /// <param name="dv">Valor inicial de la propiedad Dv.</param>
        /// <param name="nombres">Valor inicial de la propiedad Nombres.</param>
        /// <param name="apellidos">Valor inicial de la propiedad Apellidos.</param>
        /// <param name="empresa">Valor inicial de la propiedad Empresa.</param>
        public static Empleado CreateEmpleado(global::System.Int32 rut, global::System.String dv, global::System.String nombres, global::System.String apellidos, global::System.Int32 empresa)
        {
            Empleado empleado = new Empleado();
            empleado.Rut = rut;
            empleado.Dv = dv;
            empleado.Nombres = nombres;
            empleado.Apellidos = apellidos;
            empleado.Empresa = empresa;
            return empleado;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rut
        {
            get
            {
                return _Rut;
            }
            set
            {
                if (_Rut != value)
                {
                    OnRutChanging(value);
                    ReportPropertyChanging("Rut");
                    _Rut = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Rut");
                    OnRutChanged();
                }
            }
        }
        private global::System.Int32 _Rut;
        partial void OnRutChanging(global::System.Int32 value);
        partial void OnRutChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Dv
        {
            get
            {
                return _Dv;
            }
            set
            {
                OnDvChanging(value);
                ReportPropertyChanging("Dv");
                _Dv = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Dv");
                OnDvChanged();
            }
        }
        private global::System.String _Dv;
        partial void OnDvChanging(global::System.String value);
        partial void OnDvChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombres
        {
            get
            {
                return _Nombres;
            }
            set
            {
                OnNombresChanging(value);
                ReportPropertyChanging("Nombres");
                _Nombres = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombres");
                OnNombresChanged();
            }
        }
        private global::System.String _Nombres;
        partial void OnNombresChanging(global::System.String value);
        partial void OnNombresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellidos
        {
            get
            {
                return _Apellidos;
            }
            set
            {
                OnApellidosChanging(value);
                ReportPropertyChanging("Apellidos");
                _Apellidos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellidos");
                OnApellidosChanged();
            }
        }
        private global::System.String _Apellidos;
        partial void OnApellidosChanging(global::System.String value);
        partial void OnApellidosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Empresa
        {
            get
            {
                return _Empresa;
            }
            set
            {
                OnEmpresaChanging(value);
                ReportPropertyChanging("Empresa");
                _Empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Empresa");
                OnEmpresaChanged();
            }
        }
        private global::System.Int32 _Empresa;
        partial void OnEmpresaChanging(global::System.Int32 value);
        partial void OnEmpresaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmpresasModel", "Empresa_Empleado_FK1", "Empresa")]
        public Empresa Empresa1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("EmpresasModel.Empresa_Empleado_FK1", "Empresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("EmpresasModel.Empresa_Empleado_FK1", "Empresa").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empresa> Empresa1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("EmpresasModel.Empresa_Empleado_FK1", "Empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empresa>("EmpresasModel.Empresa_Empleado_FK1", "Empresa", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmpresasModel", Name="Empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empresa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empresa.
        /// </summary>
        /// <param name="rut">Valor inicial de la propiedad Rut.</param>
        /// <param name="dv">Valor inicial de la propiedad Dv.</param>
        /// <param name="razonSocial">Valor inicial de la propiedad RazonSocial.</param>
        public static Empresa CreateEmpresa(global::System.Int32 rut, global::System.String dv, global::System.String razonSocial)
        {
            Empresa empresa = new Empresa();
            empresa.Rut = rut;
            empresa.Dv = dv;
            empresa.RazonSocial = razonSocial;
            return empresa;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rut
        {
            get
            {
                return _Rut;
            }
            set
            {
                if (_Rut != value)
                {
                    OnRutChanging(value);
                    ReportPropertyChanging("Rut");
                    _Rut = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Rut");
                    OnRutChanged();
                }
            }
        }
        private global::System.Int32 _Rut;
        partial void OnRutChanging(global::System.Int32 value);
        partial void OnRutChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Dv
        {
            get
            {
                return _Dv;
            }
            set
            {
                OnDvChanging(value);
                ReportPropertyChanging("Dv");
                _Dv = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Dv");
                OnDvChanged();
            }
        }
        private global::System.String _Dv;
        partial void OnDvChanging(global::System.String value);
        partial void OnDvChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmpresasModel", "Empresa_Empleado_FK1", "Empleado")]
        public EntityCollection<Empleado> Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("EmpresasModel.Empresa_Empleado_FK1", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("EmpresasModel.Empresa_Empleado_FK1", "Empleado", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
